name: whatsapp-electron
base: core22
version: '1.0.1'
summary: Whatsapp Desktop
description: |
  Unofficial Whatsapp client for Linux using Electron and Whatsapp Web

grade: stable
confinement: strict

parts:
  my-part:
    npm-include-node: true
    npm-node-version: "20.14.0"
    plugin: npm
    source: .
