# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: sudo snap install snapcraft --classic
    - run: echo ${{secrets.SNAPCRAFT_STORE_CREDENTIALS}} | snapcraft login --with -
    - run: npm run publish
    # - name: Install Snapcraft
    #   uses: samuelmeuli/action-snapcraft@v2
    # - name: Use Snapcraft
    #   run: snapcraft upload --release=candidate dist/whatsapp-electron_1.0.0_amd64.snap
